service: form-service

provider:
  name: aws
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  runtime: nodejs4.3
defaults:
  stage: dev
  region: us-west-2

package:
  include:
    - project
  exclude:
    - project/package.json
    - project/env/config.json.dev
    - project/env/config.json.prod
    - project/npm-debug.log

functions:
  createContactFormFunction:
    name: ${prefix}-createContactForm
    handler: project/main.createContactForm
    events:
      - http:
          path: contact_forms
          method: POST
          cors: true
    vpc:
      securityGroupIds:
        -
          Ref: LambdaSecurityGroup
      subnetIds:
        -
          Ref: LambdaSubnet1
        -
          Ref: LambdaSubnet2
        -
          Ref: LambdaSubnet3
  deleteContactFormFunction:
    name: ${prefix}-deleteContactForm
    handler: project/main.deleteContactForm
    events:
      - http:
          path: contact_forms
          method: DELETE
          cors: true
    vpc:
      securityGroupIds:
        -
          Ref: LambdaSecurityGroup
      subnetIds:
        -
          Ref: LambdaSubnet1
        -
          Ref: LambdaSubnet2
        -
          Ref: LambdaSubnet3
  listContactFormsFunction:
    name: ${prefix}-listContactForms
    handler: project/main.listContactForms
    events:
      - http:
          path: contact_forms
          method: GET
          cors: true
    vpc:
      securityGroupIds:
        -
          Ref: LambdaSecurityGroup
      subnetIds:
        -
          Ref: LambdaSubnet1
        -
          Ref: LambdaSubnet2
        -
          Ref: LambdaSubnet3
  sendMessageFunction:
    name: ${prefix}-sendMessage
    handler: project/main.sendMessage
    events:
      - http:
          path: messages/send
          method: POST
          cors: true
    vpc:
      securityGroupIds:
        -
          Ref: LambdaSecurityGroup
      subnetIds:
        -
          Ref: LambdaSubnet1
        -
          Ref: LambdaSubnet2
        -
          Ref: LambdaSubnet3
  processMessagesFunction:
    name: ${prefix}-processMessages
    handler: project/main.processMessages
    events:
      - schedule: rate(2 hours)
    vpc:
      securityGroupIds:
        -
          Ref: LambdaSecurityGroup
      subnetIds:
        -
          Ref: LambdaSubnet1
        -
          Ref: LambdaSubnet2
        -
          Ref: LambdaSubnet3
  setupDatabaseFunction:
    name: ${prefix}-setupDatabase
    handler: project/main.setupDatabase
    vpc:
      securityGroupIds:
        -
          Ref: LambdaSecurityGroup
      subnetIds:
        -
          Ref: LambdaSubnet1
        -
          Ref: LambdaSubnet2
        -
          Ref: LambdaSubnet3

resources:
  Resources:
    $ref: custom_resources/resources.json
